In [18]:
from pathlib import Path
import pandas as pd
from cyvcf2 import VCF
from tqdm import tqdm

In [19]:
pd.set_option('display.max_columns', None)

In [20]:
snp_only_dir = Path("./snp_only")

vcf_files = sorted(snp_only_dir.glob("*.vcf"))

In [21]:
# Collect all unique SNP sites across samples 
all_sites = set()
sample_sites = {}

print("🔍 Reading SNP sites from all VCFs...")
for vcf_file in tqdm(vcf_files):
    sample_name = vcf_file.stem.replace("_snps_only", "")
    reader = VCF(str(vcf_file))
    sites = []
    for record in reader:
        # Use (CHROM, POS, REF, ALT) tuple for uniqueness
        for alt in record.ALT:
            site = (record.CHROM, record.POS, record.REF, str(alt))
            sites.append(site)
            all_sites.add(site)
    sample_sites[sample_name] = sites

all_sites = sorted(all_sites)

print(f"✅ Total unique SNP sites: {len(all_sites)}")

🔍 Reading SNP sites from all VCFs...

100%|██████████| 400/400 [04:00<00:00,  1.66it/s]

✅ Total unique SNP sites: 1710

In [22]:
matrix = []
for sample_name, sites in tqdm(sample_sites.items(), desc="🧬 Building SNP matrix"):
    sites_set = set(sites)
    row = [1 if site in sites_set else 0 for site in all_sites]
    matrix.append(row)

columns = [f"{chrom}_{pos}_{ref}_{alt}" for chrom, pos, ref, alt in all_sites]
df = pd.DataFrame(matrix, columns=columns, index=sample_sites.keys())

print("✅ SNP Matrix shape:", df.shape)

🧬 Building SNP matrix:   0%|          | 0/400 [00:00<?, ?it/s]

🧬 Building SNP matrix: 100%|██████████| 400/400 [00:00<00:00, 3551.05it/s]

✅ SNP Matrix shape: (400, 1710)

In [23]:
df.to_csv("snp_matrix.csv")
print("📁 Saved SNP matrix to snp_matrix.csv")

📁 Saved SNP matrix to snp_matrix.csv

In [24]:
df

,Chromosome_71_C_T,Chromosome_82_G_C,Chromosome_195_G_C,Chromosome_252_C_A,Chromosome_266_G_A,Chromosome_290_G_C,Chromosome_309_G_C,Chromosome_371_C_T,Chromosome_467_A_G,Chromosome_485_C_T,Chromosome_526_A_G,Chromosome_645_A_C,Chromosome_672_T_C,Chromosome_697_C_T,Chromosome_698_G_A,Chromosome_758_A_C,Chromosome_1100_G_A,Chromosome_1186_G_A,Chromosome_1199_G_A,Chromosome_1274_A_C,Chromosome_1284_C_A,Chromosome_1294_C_T,Chromosome_1302_C_A,Chromosome_1326_G_T,Chromosome_1389_C_T,Chromosome_1519_C_T,Chromosome_1524_G_T,Chromosome_5075_C_T,Chromosome_5436_A_G,Chromosome_5461_T_C,Chromosome_5489_A_G,Chromosome_5520_C_T,Chromosome_5627_G_T,Chromosome_5731_C_T,Chromosome_5752_G_A,Chromosome_5858_A_G,Chromosome_6052_T_G,Chromosome_6090_G_C,Chromosome_6112_G_C,Chromosome_6124_C_T,Chromosome_6140_G_T,Chromosome_6317_G_A,Chromosome_6370_C_T,Chromosome_6406_C_T,Chromosome_6438_C_G,Chromosome_6446_G_T,Chromosome_6507_C_T,Chromosome_6576_G_A,Chromosome_6735_A_C,Chromosome_6736_C_T,Chromosome_6741_A_G,Chromosome_6742_A_C,Chromosome_6750_C_T,Chromosome_6815_A_C,Chromosome_6859_T_C,Chromosome_6950_C_A,Chromosome_6963_G_A,Chromosome_7042_C_T,Chromosome_7121_C_G,Chromosome_7151_C_G,Chromosome_7221_G_C,Chromosome_7222_C_T,Chromosome_7232_C_T,Chromosome_7247_G_T,Chromosome_7268_C_T,Chromosome_7283_G_T,Chromosome_7362_G_C,Chromosome_7438_A_G,Chromosome_7570_C_T,Chromosome_7572_T_C,Chromosome_7581_G_A,Chromosome_7581_G_C,Chromosome_7581_G_T,Chromosome_7582_A_C,Chromosome_7582_A_G,Chromosome_7585_G_C,Chromosome_7892_G_A,Chromosome_7901_G_T,Chromosome_8040_G_A,Chromosome_8056_G_T,Chromosome_8135_C_T,Chromosome_8164_C_A,Chromosome_8195_C_T,Chromosome_8285_C_T,Chromosome_8306_C_A,Chromosome_8336_G_C,Chromosome_8353_G_C,Chromosome_8364_A_T,Chromosome_8400_G_C,Chromosome_8414_C_T,Chromosome_8437_A_G,Chromosome_8452_C_T,Chromosome_8486_T_C,Chromosome_8534_G_A,Chromosome_8624_G_T,Chromosome_8688_G_T,Chromosome_8715_C_T,Chromosome_8741_C_T,Chromosome_8795_C_T,Chromosome_8879_C_T,Chromosome_8948_G_A,Chromosome_8957_C_T,Chromosome_9047_C_T,Chromosome_9138_C_G,Chromosome_9143_T_C,Chromosome_9171_G_C,Chromosome_9260_G_C,Chromosome_9272_C_T,Chromosome_9304_G_A,Chromosome_9344_C_T,Chromosome_9395_G_A,Chromosome_9443_G_A,Chromosome_9532_G_C,Chromosome_9557_G_C,Chromosome_9566_C_T,Chromosome_9620_G_A,Chromosome_9656_C_G,Chromosome_13149_C_T,Chromosome_13175_A_G,Chromosome_13197_G_C,Chromosome_13275_T_C,Chromosome_13298_G_C,Chromosome_13423_C_G,Chromosome_13458_G_T,Chromosome_13460_A_G,Chromosome_13482_G_A,Chromosome_13502_C_A,Chromosome_13503_C_A,Chromosome_13507_C_T,Chromosome_13529_G_A,Chromosome_13543_A_G,Chromosome_13556_C_G,Chromosome_13579_C_T,Chromosome_13624_G_A,Chromosome_13627_T_C,Chromosome_13630_C_T,Chromosome_13636_T_C,Chromosome_13646_T_C,Chromosome_13647_G_A,Chromosome_13677_C_A,Chromosome_13699_T_C,Chromosome_13705_C_T,Chromosome_13808_G_A,Chromosome_13852_T_C,Chromosome_13905_C_A,Chromosome_490552_G_T,Chromosome_490696_T_C,Chromosome_490756_T_G,Chromosome_490857_C_T,Chromosome_490938_G_A,Chromosome_490972_C_A,Chromosome_491100_C_T,Chromosome_491142_C_T,Chromosome_491174_G_A,Chromosome_491247_C_T,Chromosome_491290_G_A,Chromosome_491334_C_T,Chromosome_491384_A_G,Chromosome_491429_C_G,Chromosome_491556_G_A,Chromosome_491591_A_T,Chromosome_491659_G_A,Chromosome_491742_T_C,Chromosome_574538_C_T,Chromosome_574675_C_T,Chromosome_574862_T_C,Chromosome_574894_C_T,Chromosome_574895_T_G,Chromosome_575368_T_C,Chromosome_575434_C_T,Chromosome_575490_C_T,Chromosome_575664_G_C,Chromosome_575679_A_G,Chromosome_575837_C_T,Chromosome_575907_C_T,Chromosome_576000_A_C,Chromosome_576077_C_T,Chromosome_576400_C_T,Chromosome_576508_C_A,Chromosome_576555_A_G,Chromosome_576683_G_A,Chromosome_619687_G_A,Chromosome_619903_C_A,Chromosome_620029_C_T,Chromosome_620111_A_C,Chromosome_620172_C_T,Chromosome_620418_G_A,Chromosome_620553_T_C,Chromosome_620600_T_C,Chromosome_620625_A_G,Chromosome_656120_G_T,Chromosome_656312_A_G,Chromosome_656367_C_T,Chromosome_656427_C_A,Chromosome_656856_C_T,Chromosome_657066_G_A,Chromosome_657081_C_T,Chromosome_657099_G_A,Chromosome_657142_C_T,Chromosome_657230_C_T,Chromosome_657269_A_G,Chromosome_657334_A_G,Chromosome_657360_G_A,Chromosome_657370_T_C,Chromosome_657425_C_T,Chromosome_657494_G_T,Chromosome_657578_A_G,Chromosome_657730_T_G,Chromosome_731750_G_C,Chromosome_731776_A_G,Chromosome_731980_C_T,Chromosome_731988_T_C,Chromosome_732036_A_G,Chromosome_732063_C_T,Chromosome_732110_T_G,Chromosome_732145_C_T,Chromosome_732154_G_C,Chromosome_732226_G_A,Chromosome_732251_T_C,Chromosome_734116_T_C,Chromosome_734261_C_A,Chromosome_734446_A_C,Chromosome_734467_A_C,Chromosome_734538_C_G,Chromosome_734624_G_T,Chromosome_734658_A_G,Chromosome_734735_C_T,Chromosome_734866_A_G,Chromosome_734938_G_A,Chromosome_737281_G_A,Chromosome_737857_C_T,Chromosome_738071_C_T,Chromosome_738135_T_C,Chromosome_738201_C_A,Chromosome_738255_T_G,Chromosome_738269_C_G,Chromosome_759485_G_A,Chromosome_759546_A_G,Chromosome_759590_A_G,Chromosome_759608_C_T,Chromosome_759668_A_G,Chromosome_759697_A_G,Chromosome_759746_C_T,Chromosome_759786_G_C,Chromosome_760013_C_T,Chromosome_760085_C_T,Chromosome_760098_T_G,Chromosome_760106_G_A,Chromosome_760115_C_T,Chromosome_760142_C_T,Chromosome_760314_G_T,Chromosome_760490_C_T,Chromosome_760755_C_T,Chromosome_760835_C_G,Chromosome_760975_T_C,Chromosome_761069_C_T,Chromosome_761085_A_G,Chromosome_761095_T_C,Chromosome_761095_T_G,Chromosome_761101_A_C,Chromosome_761109_G_T,Chromosome_761110_A_G,Chromosome_761110_A_T,Chromosome_761139_C_A,Chromosome_761139_C_G,Chromosome_761139_C_T,Chromosome_761140_A_G,Chromosome_761140_A_T,Chromosome_761155_C_G,Chromosome_761155_C_T,Chromosome_761161_T_C,Chromosome_761244_A_G,Chromosome_761277_A_C,Chromosome_761277_A_T,Chromosome_761292_G_A,Chromosome_761461_G_T,Chromosome_761489_G_A,Chromosome_761568_A_G,Chromosome_761707_A_G,Chromosome_761786_C_T,Chromosome_761847_T_G,Chromosome_761880_G_A,Chromosome_761889_G_C,Chromosome_761998_T_C,Chromosome_762072_A_G,Chromosome_762089_G_C,Chromosome_762177_C_T,Chromosome_762434_T_G,Chromosome_762441_C_T,Chromosome_762477_A_G,Chromosome_762633_G_A,Chromosome_762847_C_G,Chromosome_763031_T_C,Chromosome_763501_C_A,Chromosome_763531_G_C,Chromosome_763555_C_T,Chromosome_763575_G_C,Chromosome_763644_T_C,Chromosome_763884_C_T,Chromosome_763886_C_A,Chromosome_763887_G_A,Chromosome_764263_G_A,Chromosome_764277_A_T,Chromosome_764335_G_A,Chromosome_764363_G_A,Chromosome_764363_G_C,Chromosome_764532_G_C,Chromosome_764608_C_T,Chromosome_764653_G_A,Chromosome_764666_G_A,Chromosome_764670_C_T,Chromosome_764724_T_C,Chromosome_764817_T_C,Chromosome_764817_T_G,Chromosome_764822_G_A,Chromosome_764840_A_G,Chromosome_764841_T_C,Chromosome_764888_T_G,Chromosome_764916_T_C,Chromosome_764918_G_C,Chromosome_764924_G_A,Chromosome_764931_C_A,Chromosome_764995_C_G,Chromosome_765008_T_G,Chromosome_765035_C_T,Chromosome_765046_G_A,Chromosome_765080_G_C,Chromosome_765150_G_A,Chromosome_765171_C_T,Chromosome_765187_C_T,Chromosome_765222_C_T,Chromosome_765230_G_A,Chromosome_765311_G_A,Chromosome_765352_G_A,Chromosome_765462_A_G,Chromosome_765590_C_A,Chromosome_765608_G_A,Chromosome_765616_C_T,Chromosome_765753_A_G,Chromosome_765804_C_T,Chromosome_765920_A_G,Chromosome_765988_G_A,Chromosome_766012_C_G,Chromosome_766085_C_G,Chromosome_766095_C_A,Chromosome_766237_T_C,Chromosome_766485_T_G,Chromosome_766487_C_G,Chromosome_766488_C_G,Chromosome_766582_C_A,Chromosome_766645_A_C,Chromosome_766678_C_T,Chromosome_767007_C_A,Chromosome_767123_G_A,Chromosome_767149_C_T,Chromosome_775639_T_C,Chromosome_775700_C_A,Chromosome_775746_A_G,Chromosome_776006_G_A,Chromosome_776100_G_A,Chromosome_776181_T_G,Chromosome_776182_C_T,Chromosome_776395_A_G,Chromosome_776445_G_T,Chromosome_776573_C_T,Chromosome_776723_G_A,Chromosome_776826_T_C,Chromosome_776855_G_A,Chromosome_776891_C_A,Chromosome_777050_C_G,Chromosome_777320_G_C,Chromosome_777416_C_A,Chromosome_777581_G_T,Chromosome_777974_G_A,Chromosome_778042_C_T,Chromosome_778152_T_C,Chromosome_778178_G_A,Chromosome_778298_C_T,Chromosome_778463_T_C,Chromosome_778624_G_A,Chromosome_778883_G_A,Chromosome_778896_T_G,Chromosome_778979_C_A,Chromosome_779084_T_C,Chromosome_779346_C_A,Chromosome_779374_C_T,Chromosome_779406_G_T,Chromosome_779526_C_T,Chromosome_779609_G_A,Chromosome_779615_G_C,Chromosome_781158_C_G,Chromosome_781273_G_A,Chromosome_781276_A_C,Chromosome_781301_C_T,Chromosome_781395_T_C,Chromosome_781421_C_A,Chromosome_781435_G_C,Chromosome_781458_C_T,Chromosome_781568_C_T,Chromosome_781676_C_T,Chromosome_781687_A_G,Chromosome_781694_G_A,Chromosome_781746_G_A,Chromosome_781822_A_C,Chromosome_781822_A_G,Chromosome_800135_G_A,Chromosome_800200_C_G,Chromosome_800204_T_C,Chromosome_800219_T_C,Chromosome_800231_C_T,Chromosome_800238_A_G,Chromosome_800250_C_G,Chromosome_800287_G_C,Chromosome_800349_C_G,Chromosome_800357_C_A,Chromosome_800793_G_C,Chromosome_800889_C_A,Chromosome_801009_A_G,Chromosome_801210_T_G,Chromosome_801244_C_A,Chromosome_801268_T_C,Chromosome_1253087_T_G,Chromosome_1253118_C_T,Chromosome_1253245_G_A,Chromosome_1253304_T_A,Chromosome_1253314_G_A,Chromosome_1253440_C_T,Chromosome_1253454_C_A,Chromosome_1253454_C_T,Chromosome_1253456_C_A,Chromosome_1253568_T_C,Chromosome_1253930_A_T,Chromosome_1254056_T_G,Chromosome_1254131_T_C,Chromosome_1254335_T_G,Chromosome_1254521_T_C,Chromosome_1254543_A_C,Chromosome_1254549_C_T,Chromosome_1254551_A_C,Chromosome_1254552_A_C,Chromosome_1254562_A_G,Chromosome_1254575_A_G,Chromosome_1254576_G_A,Chromosome_1254580_G_C,Chromosome_1254582_T_C,Chromosome_1254583_T_G,Chromosome_1254588_A_C,Chromosome_1254623_G_T,Chromosome_1254625_G_A,Chromosome_1254627_A_G,Chromosome_1254644_G_A,Chromosome_1302747_T_G,Chromosome_1302782_C_T,Chromosome_1302814_C_T,Chromosome_1302873_A_C,Chromosome_1302899_A_G,Chromosome_1302901_G_A,Chromosome_1302927_C_T,Chromosome_1303230_C_A,Chromosome_1303329_C_T,Chromosome_1303476_G_C,Chromosome_1303601_A_G,Chromosome_1303612_C_T,Chromosome_1303897_C_T,Chromosome_1304355_G_A,Chromosome_1304451_C_T,Chromosome_1304610_C_T,Chromosome_1304671_G_C,Chromosome_1304788_G_A,Chromosome_1305243_T_G,Chromosome_1305376_A_G,Chromosome_1305409_G_T,Chromosome_1364170_C_T,Chromosome_1364205_G_C,Chromosome_1364267_G_A,Chromosome_1364336_G_A,Chromosome_1364434_C_T,Chromosome_1364633_C_T,Chromosome_1364706_G_A,Chromosome_1364961_A_C,Chromosome_1365069_C_T,Chromosome_1365072_G_T,Chromosome_1365148_C_T,Chromosome_1406101_G_A,Chromosome_1406137_C_G,Chromosome_1406179_C_T,Chromosome_1406312_A_G,Chromosome_1406451_G_A,Chromosome_1406503_C_G,Chromosome_1406613_T_G,Chromosome_1406813_A_G,Chromosome_1406837_A_T,Chromosome_1406860_C_T,Chromosome_1406963_C_T,Chromosome_1407032_C_T,Chromosome_1407102_G_A,Chromosome_1407180_G_A,Chromosome_1407273_T_A,Chromosome_1407356_A_G,Chromosome_1416490_C_A,Chromosome_1416500_G_C,Chromosome_1416523_C_G,Chromosome_1416699_G_C,Chromosome_1416710_G_C,Chromosome_1416960_G_A,Chromosome_1416981_C_T,Chromosome_1417019_C_T,Chromosome_1417140_C_A,Chromosome_1417140_C_T,Chromosome_1417150_C_T,Chromosome_1417152_A_C,Chromosome_1417554_G_C,Chromosome_1417688_G_A,Chromosome_1417753_T_G,Chromosome_1417793_G_A,Chromosome_1417982_G_C,Chromosome_1417985_G_T,Chromosome_1418018_G_A,Chromosome_1460907_T_C,Chromosome_1460927_C_T,Chromosome_1460992_A_C,Chromosome_1471607_G_A,Chromosome_1471620_C_G,Chromosome_1471644_T_C,Chromosome_1471653_C_T,Chromosome_1471659_C_T,Chromosome_1471669_C_T,Chromosome_1471777_C_T,Chromosome_1471841_T_G,Chromosome_1472286_C_T,Chromosome_1472337_C_T,Chromosome_1472358_C_T,Chromosome_1472359_A_C,Chromosome_1472362_C_T,Chromosome_1472530_G_A,Chromosome_1472537_C_T,Chromosome_1472544_C_A,Chromosome_1472545_A_T,Chromosome_1472566_G_A,Chromosome_1472571_G_C,Chromosome_1472579_G_C,Chromosome_1472579_G_T,Chromosome_1472580_C_T,Chromosome_1472581_A_T,Chromosome_1472598_A_C,Chromosome_1472599_G_T,Chromosome_1472616_G_A,Chromosome_1472733_G_A,Chromosome_1472742_C_T,Chromosome_1472744_A_G,Chromosome_1472753_A_C,Chromosome_1473021_G_A,Chromosome_1473088_A_G,Chromosome_1473093_C_T,Chromosome_1473104_C_T,Chromosome_1473121_T_C,Chromosome_1473246_A_G,Chromosome_1473288_C_G,Chromosome_1473368_G_A,Chromosome_1473637_A_G,Chromosome_1473640_C_T,Chromosome_1473751_C_T,Chromosome_1474001_C_T,Chromosome_1474232_C_T,Chromosome_1474234_G_A,Chromosome_1474464_C_T,Chromosome_1474639_G_A,Chromosome_1474709_G_T,Chromosome_1474963_G_T,Chromosome_1475265_G_A,Chromosome_1475284_C_G,Chromosome_1475395_T_C,Chromosome_1475972_C_T,Chromosome_1475998_C_A,Chromosome_1476056_G_A,Chromosome_1476083_T_G,Chromosome_1476573_A_G,Chromosome_1476710_C_T,Chromosome_1673194_G_A,Chromosome_1673249_C_T,Chromosome_1673338_G_A,Chromosome_1673423_G_T,Chromosome_1673425_C_T,Chromosome_1673432_T_A,Chromosome_1673432_T_C,Chromosome_1674048_G_A,Chromosome_1674162_C_T,Chromosome_1674210_A_C,Chromosome_1674481_T_G,Chromosome_1674782_T_C,Chromosome_1674943_G_A,Chromosome_1833340_G_C,Chromosome_1833474_C_T,Chromosome_1833795_A_G,Chromosome_1833815_A_G,Chromosome_1833909_A_C,Chromosome_1834028_C_T,Chromosome_1834159_G_A,Chromosome_1834168_C_T,Chromosome_1834177_A_C,Chromosome_1834273_C_T,Chromosome_1834319_G_A,Chromosome_1834378_T_C,Chromosome_1834446_C_T,Chromosome_1834683_C_T,Chromosome_1834688_A_G,Chromosome_1834806_A_C,Chromosome_1834836_T_C,Chromosome_1834859_G_A,Chromosome_1853490_C_G,Chromosome_1853565_G_A,Chromosome_1853577_G_A,Chromosome_1853597_G_C,Chromosome_1853629_G_A,Chromosome_1853669_C_T,Chromosome_1853674_G_A,Chromosome_1853974_C_T,Chromosome_1854045_A_G,Chromosome_1854070_C_T,Chromosome_1854169_A_C,Chromosome_1854209_C_T,Chromosome_1854230_C_T,Chromosome_1854241_C_G,Chromosome_1854268_C_G,Chromosome_1854274_C_T,Chromosome_1854300_T_C,Chromosome_1854304_G_T,Chromosome_1854305_T_C,Chromosome_1854348_T_C,Chromosome_1854353_C_T,Chromosome_1917792_G_A,Chromosome_1917972_A_G,Chromosome_1918104_G_A,Chromosome_1918223_G_A,Chromosome_1918584_A_C,Chromosome_1918634_G_A,Chromosome_1918647_T_G,Chromosome_1918696_G_C,Chromosome_2062829_C_T,Chromosome_2062922_T_C,Chromosome_2063092_T_G,Chromosome_2063106_C_T,Chromosome_2063187_G_A,Chromosome_2063243_A_C,Chromosome_2063247_C_T,Chromosome_2063521_C_T,Chromosome_2063685_C_T,Chromosome_2063911_A_G,Chromosome_2064222_C_T,Chromosome_2064417_C_T,Chromosome_2064570_C_T,Chromosome_2064592_G_C,Chromosome_2064868_A_C,Chromosome_2101831_C_T,Chromosome_2101833_G_A,Chromosome_2101836_A_G,Chromosome_2101921_C_T,Chromosome_2102095_G_A,Chromosome_2102106_C_G,Chromosome_2102240_C_T,Chromosome_2102374_C_T,Chromosome_2102417_G_A,Chromosome_2102438_C_T,Chromosome_2102523_T_C,Chromosome_2102863_G_A,Chromosome_2102990_A_G,Chromosome_2103112_C_A,Chromosome_2103221_G_A,Chromosome_2103226_G_C,Chromosome_2103234_C_A,Chromosome_2154023_C_G,Chromosome_2154038_T_G,Chromosome_2154239_T_G,Chromosome_2154291_C_G,Chromosome_2154335_C_A,Chromosome_2154441_C_G,Chromosome_2154459_G_A,Chromosome_2154688_G_A,Chromosome_2154695_C_G,Chromosome_2154724_C_A,Chromosome_2154855_G_A,Chromosome_2154915_T_C,Chromosome_2155017_C_T,Chromosome_2155021_A_G,Chromosome_2155051_G_A,Chromosome_2155080_C_T,Chromosome_2155131_T_C,Chromosome_2155163_T_C,Chromosome_2155167_G_T,Chromosome_2155168_C_G,Chromosome_2155168_C_T,Chromosome_2155389_G_C,Chromosome_2155399_T_G,Chromosome_2155479_G_A,Chromosome_2155503_G_A,Chromosome_2155541_A_C,Chromosome_2155617_A_G,Chromosome_2155697_C_T,Chromosome_2155700_T_G,Chromosome_2155814_G_T,Chromosome_2155876_T_G,Chromosome_2155931_C_A,Chromosome_2156007_G_A,Chromosome_2156025_G_T,Chromosome_2156086_G_T,Chromosome_2156117_T_C,Chromosome_2156173_G_T,Chromosome_2156192_C_T,Chromosome_2156196_G_A,Chromosome_2156389_C_G,Chromosome_2156465_G_A,Chromosome_2156534_C_T,Chromosome_2156552_G_A,Chromosome_2156604_T_C,Chromosome_2156618_G_C,Chromosome_2156631_A_G,Chromosome_2156663_C_T,Chromosome_2167691_G_A,Chromosome_2167710_G_A,Chromosome_2167770_C_A,Chromosome_2167823_G_A,Chromosome_2167926_A_G,Chromosome_2167982_G_A,Chromosome_2167983_C_T,Chromosome_2168011_T_G,Chromosome_2168080_T_C,Chromosome_2168124_C_T,Chromosome_2168149_G_A,Chromosome_2168298_G_A,Chromosome_2168303_C_A,Chromosome_2168357_A_T,Chromosome_2168420_G_T,Chromosome_2168479_T_G,Chromosome_2168524_C_T,Chromosome_2168552_A_G,Chromosome_2168565_G_A,Chromosome_2168567_T_G,Chromosome_2168600_C_T,Chromosome_2168604_G_A,Chromosome_2168742_C_T,Chromosome_2168754_A_G,Chromosome_2168757_T_C,Chromosome_2168863_G_A,Chromosome_2168920_C_A,Chromosome_2168998_T_C,Chromosome_2169007_A_G,Chromosome_2169053_A_G,Chromosome_2169059_C_T,Chromosome_2169063_A_G,Chromosome_2169065_C_T,Chromosome_2169067_C_T,Chromosome_2169068_C_A,Chromosome_2169192_G_C,Chromosome_2169221_A_G,Chromosome_2169369_C_G,Chromosome_2169383_G_C,Chromosome_2169608_G_T,Chromosome_2169630_T_C,Chromosome_2169744_G_A,Chromosome_2169757_T_C,Chromosome_2169776_G_T,Chromosome_2169840_C_T,Chromosome_2169879_A_C,Chromosome_2169991_C_T,Chromosome_2170032_C_T,Chromosome_2170198_C_T,Chromosome_2170219_C_A,Chromosome_2170461_C_T,Chromosome_2170556_C_A,Chromosome_2170559_C_G,Chromosome_2170568_G_C,Chromosome_2170599_A_G,Chromosome_2170623_C_T,Chromosome_2170654_T_C,Chromosome_2170774_A_G,Chromosome_2170792_A_G,Chromosome_2170826_A_G,Chromosome_2170892_C_T,Chromosome_2221889_C_T,Chromosome_2221939_C_T,Chromosome_2222159_G_A,Chromosome_2222308_T_C,Chromosome_2222604_G_A,Chromosome_2222640_C_A,Chromosome_2222813_A_C,Chromosome_2222915_C_T,Chromosome_2222973_G_A,Chromosome_2222981_C_T,Chromosome_2223010_A_C,Chromosome_2223051_C_G,Chromosome_2223053_C_T,Chromosome_2223102_C_T,Chromosome_2223123_C_T,Chromosome_2223137_C_A,Chromosome_2223144_T_G,Chromosome_2223147_C_T,Chromosome_2223214_T_G,Chromosome_2223257_C_G,Chromosome_2223293_T_C,Chromosome_2223372_G_C,Chromosome_2223444_C_T,Chromosome_2223445_G_T,Chromosome_2223491_G_T,Chromosome_2223550_G_A,Chromosome_2223553_G_T,Chromosome_2223557_A_G,Chromosome_2223604_G_A,Chromosome_2223758_T_C,Chromosome_2288704_C_A,Chromosome_2288739_G_T,Chromosome_2288751_G_T,Chromosome_2288752_A_G,Chromosome_2288805_G_A,Chromosome_2288806_C_T,Chromosome_2288818_T_C,Chromosome_2288820_T_G,Chromosome_2288826_A_G,Chromosome_2288835_T_C,Chromosome_2288836_C_A,Chromosome_2288839_T_G,Chromosome_2288841_G_A,Chromosome_2288847_C_G,Chromosome_2288847_C_T,Chromosome_2288920_C_G,Chromosome_2288933_G_T,Chromosome_2288937_G_A,Chromosome_2289016_T_G,Chromosome_2289027_C_A,Chromosome_2289029_A_C,Chromosome_2289030_T_C,Chromosome_2289030_T_G,Chromosome_2289031_G_A,Chromosome_2289037_G_A,Chromosome_2289039_C_A,Chromosome_2289040_A_G,Chromosome_2289047_G_A,Chromosome_2289067_A_G,Chromosome_2289070_A_G,Chromosome_2289072_T_C,Chromosome_2289073_G_C,Chromosome_2289081_G_A,Chromosome_2289090_T_C,Chromosome_2289096_T_G,Chromosome_2289099_T_G,Chromosome_2289137_C_T,Chromosome_2289140_G_C,Chromosome_2289162_A_G,Chromosome_2289189_G_T,Chromosome_2289213_T_C,Chromosome_2289216_A_C,Chromosome_2289226_T_G,Chromosome_2289228_A_C,Chromosome_2289228_A_G,Chromosome_2289231_A_G,Chromosome_2289252_T_C,Chromosome_2289254_C_A,Chromosome_2289469_G_C,Chromosome_2289559_A_C,Chromosome_2289642_T_C,Chromosome_2289909_C_T,Chromosome_2290062_C_T,Chromosome_2290113_C_T,Chromosome_2290198_G_A,Chromosome_2290199_G_C,Chromosome_2290302_C_T,Chromosome_2518076_C_T,Chromosome_2518132_C_T,Chromosome_2518218_G_A,Chromosome_2518235_A_G,Chromosome_2518386_G_T,Chromosome_2518871_C_T,Chromosome_2518919_G_A,Chromosome_2519024_G_A,Chromosome_2519035_C_T,Chromosome_2519048_G_A,Chromosome_2519100_C_T,Chromosome_2714130_C_G,Chromosome_2714474_T_C,Chromosome_2714668_C_G,Chromosome_2714669_C_T,Chromosome_2714735_G_C,Chromosome_2714846_C_T,Chromosome_2714955_G_A,Chromosome_2714982_T_G,Chromosome_2715076_G_A,Chromosome_2715311_G_A,Chromosome_2715342_C_T,Chromosome_2715344_G_A,Chromosome_2715346_G_A,Chromosome_2715369_C_A,Chromosome_2715432_G_A,Chromosome_2715432_G_C,Chromosome_2715565_G_A,Chromosome_2726051_G_A,Chromosome_2726104_T_A,Chromosome_2726105_G_A,Chromosome_2726112_C_T,Chromosome_2726117_T_A,Chromosome_2726139_C_T,Chromosome_2726141_C_A,

# Filtering based on Minor Allele Frequency (MAF)

## What is MAF?

| Aspect                | Minor Allele Frequency (MAF)                        |
| --------------------- | --------------------------------------------------- |
| **Definition**        | Frequency of less common allele in population       |
| **Range**             | 0 to 0.5                                            |
| **Why filter it?**    | To remove rare SNPs that are uninformative or noisy |
| **Common thresholds** | MAF ≥ 0.01 or MAF ≥ 0.05                            |
| **Used in**           | GWAS, machine learning, population genetics, QC     |


## Approaches

| Aspect                    | First Code (`threshold = 5`)     | Second Code (`minimum_frequency = 0.05`)   |
| ------------------------- | -------------------------------- | ------------------------------------------ |
| **Filtering Based On**    | Absolute count of samples        | Proportion of samples                      |
| **Formula**               | SNP kept if found in ≥ 5 samples | SNP kept if found in ≥ 5% of samples       |
| **More Flexible?**        | No, fixed threshold              | Yes, scales with sample size               |
| **Example**               | Keeps SNPs in ≥ 5 samples        | Keeps SNPs in ≥ `0.05 * 251 = ~20` samples |

In [31]:
# Count how many samples have each SNP (i.e., how many 1s per column)
snp_counts = df.sum(axis=0)
snp_counts

Chromosome_71_C_T         2
Chromosome_82_G_C         1
Chromosome_195_G_C        1
Chromosome_252_C_A        1
Chromosome_266_G_A        1
                         ..
Chromosome_4408358_G_C    1
Chromosome_4408413_G_A    1
Chromosome_4408430_C_T    1
Chromosome_4408456_G_C    1
Chromosome_4408459_C_T    1
Length: 1710, dtype: int64

## MAF based on sample counts

In [33]:
maf_sc_df = df.copy()
print("🔢 Initial matrix shape:", maf_sc_df.shape)

🔢 Initial matrix shape: (400, 1710)

In [34]:
# Filter threshold: keep SNPs present in >= 5 samples
threshold = 5
maf_sc_df = maf_sc_df.loc[:, snp_counts >= threshold]

print("🔢 Matrix shape after filtering rare SNPs with a 5 threshold:", maf_sc_df.shape)

🔢 Matrix shape after filtering rare SNPs with a 5 threshold: (400, 226)

In [35]:
maf_sc_df

,Chromosome_371_C_T,Chromosome_5075_C_T,Chromosome_5520_C_T,Chromosome_6112_G_C,Chromosome_6124_C_T,Chromosome_6446_G_T,Chromosome_7222_C_T,Chromosome_7268_C_T,Chromosome_7362_G_C,Chromosome_7570_C_T,Chromosome_7581_G_T,Chromosome_7582_A_C,Chromosome_7582_A_G,Chromosome_7585_G_C,Chromosome_7892_G_A,Chromosome_8040_G_A,Chromosome_8452_C_T,Chromosome_8688_G_T,Chromosome_9143_T_C,Chromosome_9260_G_C,Chromosome_9304_G_A,Chromosome_13298_G_C,Chromosome_13460_A_G,Chromosome_13482_G_A,Chromosome_13699_T_C,Chromosome_491290_G_A,Chromosome_491591_A_T,Chromosome_491742_T_C,Chromosome_575679_A_G,Chromosome_575907_C_T,Chromosome_576077_C_T,Chromosome_620029_C_T,Chromosome_620553_T_C,Chromosome_620625_A_G,Chromosome_657081_C_T,Chromosome_657142_C_T,Chromosome_657269_A_G,Chromosome_657425_C_T,Chromosome_657578_A_G,Chromosome_734116_T_C,Chromosome_759546_A_G,Chromosome_759746_C_T,Chromosome_760115_C_T,Chromosome_760490_C_T,Chromosome_761110_A_T,Chromosome_761139_C_T,Chromosome_761155_C_T,Chromosome_761489_G_A,Chromosome_762089_G_C,Chromosome_762434_T_G,Chromosome_763031_T_C,Chromosome_763884_C_T,Chromosome_763886_C_A,Chromosome_764817_T_C,Chromosome_764817_T_G,Chromosome_764840_A_G,Chromosome_764995_C_G,Chromosome_765150_G_A,Chromosome_765171_C_T,Chromosome_766488_C_G,Chromosome_766645_A_C,Chromosome_775639_T_C,Chromosome_776100_G_A,Chromosome_776182_C_T,Chromosome_776395_A_G,Chromosome_778298_C_T,Chromosome_779615_G_C,Chromosome_781276_A_C,Chromosome_781395_T_C,Chromosome_781687_A_G,Chromosome_781822_A_G,Chromosome_800204_T_C,Chromosome_800219_T_C,Chromosome_800357_C_A,Chromosome_1254562_A_G,Chromosome_1302899_A_G,Chromosome_1303601_A_G,Chromosome_1364706_G_A,Chromosome_1417019_C_T,Chromosome_1417554_G_C,Chromosome_1417793_G_A,Chromosome_1471659_C_T,Chromosome_1472337_C_T,Chromosome_1472359_A_C,Chromosome_1472362_C_T,Chromosome_1473246_A_G,Chromosome_1474001_C_T,Chromosome_1673425_C_T,Chromosome_1834177_A_C,Chromosome_1834836_T_C,Chromosome_1853974_C_T,Chromosome_1854045_A_G,Chromosome_1854169_A_C,Chromosome_1854300_T_C,Chromosome_1917972_A_G,Chromosome_2062922_T_C,Chromosome_2063187_G_A,Chromosome_2063685_C_T,Chromosome_2063911_A_G,Chromosome_2102240_C_T,Chromosome_2102990_A_G,Chromosome_2154724_C_A,Chromosome_2155168_C_G,Chromosome_2167926_A_G,Chromosome_2167983_C_T,Chromosome_2168149_G_A,Chromosome_2168604_G_A,Chromosome_2168742_C_T,Chromosome_2169840_C_T,Chromosome_2170568_G_C,Chromosome_2222308_T_C,Chromosome_2223293_T_C,Chromosome_2223372_G_C,Chromosome_2223553_G_T,Chromosome_2288847_C_G,Chromosome_2289047_G_A,Chromosome_2289162_A_G,Chromosome_2518076_C_T,Chromosome_2518132_C_T,Chromosome_2518919_G_A,Chromosome_2714846_C_T,Chromosome_2715369_C_A,Chromosome_2726051_G_A,Chromosome_2726105_G_A,Chromosome_2782498_G_A,Chromosome_2783921_C_T,Chromosome_2784617_A_G,Chromosome_2995848_G_A,Chromosome_2996208_C_A,Chromosome_2996912_C_T,Chromosome_3064632_G_A,Chromosome_3066099_C_T,Chromosome_3066280_G_A,Chromosome_3067039_A_G,Chromosome_3073868_T_C,Chromosome_3086731_A_G,Chromosome_3086742_A_C,Chromosome_3086788_T_C,Chromosome_3339417_A_G,Chromosome_3448497_T_A,Chromosome_3448567_C_G,Chromosome_3448608_G_A,Chromosome_3448714_G_C,Chromosome_3569220_G_A,Chromosome_3612009_C_T,Chromosome_3612813_T_C,Chromosome_3624350_C_A,Chromosome_3624486_T_C,Chromosome_3625065_T_G,Chromosome_3626467_C_T,Chromosome_3626562_G_A,Chromosome_3640211_T_G,Chromosome_3640557_T_C,Chromosome_3641447_C_T,Chromosome_3642877_A_G,Chromosome_3840764_C_G,Chromosome_3841473_C_T,Chromosome_3877553_C_T,Chromosome_4038287_G_A,Chromosome_4038318_G_A,Chromosome_4040517_A_G,Chromosome_4040719_T_C,Chromosome_4044740_G_A,Chromosome_4044872_G_A,Chromosome_4045645_C_T,Chromosome_4046007_C_T,Chromosome_4138377_A_G,Chromosome_4138622_G_A,Chromosome_4139246_G_A,Chromosome_4238120_G_A,Chromosome_4238675_C_T,Chromosome_4238963_C_T,Chromosome_4239298_C_T,Chromosome_4240671_C_T,Chromosome_4240897_C_G,Chromosome_4241022_C_T,Chromosome_4241042_A_G,Chromosome_4242075_G_A,Chromosome_4242182_G_T,Chromosome_4242643_C_T,Chromosome_4242803_G_C,Chromosome_4243346_A_G,Chromosome_4243460_C_T,Chromosome_4243848_G_A,Chromosome_4244220_C_T,Chromosome_4244420_G_C,Chromosome_4245969_C_T,Chromosome_4246508_G_A,Chromosome_4247429_A_G,Chromosome_4247431_G_A,Chromosome_4247431_G_C,Chromosome_4247574_A_C,Chromosome_4247646_A_C,Chromosome_4247729_G_A,Chromosome_4248003_A_G,Chromosome_4248115_C_T,Chromosome_4249408_G_A,Chromosome_4249757_A_G,Chromosome_4267272_T_C,Chromosome_4267647_T_C,Chromosome_4267960_C_T,Chromosome_4268928_G_A,Chromosome_4269375_C_T,Chromosome_4269387_T_G,Chromosome_4269540_G_A,Chromosome_4269606_A_G,Chromosome_4326148_C_A,Chromosome_4326439_G_T,Chromosome_4326676_G_C,Chromosome_4326739_G_C,Chromosome_4327480_A_G,Chromosome_4328004_G_A,Chromosome_4328492_G_A,Chromosome_4329782_G_A,Chromosome_4338203_G_A,Chromosome_4338361_C_T,Chromosome_4338371_T_G,Chromosome_4338563_C_A,Chromosome_4338603_G_A,Chromosome_4338732_G_A,Chromosome_4407588_T_C,Chromosome_4407620_A_G,Chromosome_4407848_C_T,Chromosome_4407873_C_A,Chromosome_4407927_T_G,Chromosome_4408156_A_C
ERR038257.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
ERR046771.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0
ERR046840.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
ERR046847.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0
ERR046937.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ERR4831907.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0
ERR4831952.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0
ERR4831955.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0
ERR4872232.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
ERR550776.vcf,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [36]:
df.to_csv("maf_sc_snp_matrix.csv")
print("📁 Saved SNP matrix to maf_sc_snp_matrix.csv")

📁 Saved SNP matrix to maf_sc_snp_matrix.csv

## MAF based on proportion of samples

In [39]:
maf_prop_df = df.copy()
print("🔢 Matrix shape:", maf_prop_df.shape)

🔢 Matrix shape: (400, 1710)

In [40]:
minimum_frequency = 0.05  # keep SNPs in at least 5% of samples

# Calculate allele frequency for each SNP (column)
allele_frequencies = maf_prop_df.sum(axis=0) / maf_prop_df.shape[0]

# Filter columns to keep only SNPs where frequency >= minimum_frequency
maf_prop_df = maf_prop_df.loc[:, allele_frequencies >= minimum_frequency]

print(f"Filtered SNP matrix shape: {maf_prop_df.shape}")

maf_prop_df

Filtered SNP matrix shape: (400, 101)

,Chromosome_6112_G_C,Chromosome_7362_G_C,Chromosome_7582_A_G,Chromosome_7585_G_C,Chromosome_8452_C_T,Chromosome_9143_T_C,Chromosome_9304_G_A,Chromosome_13298_G_C,Chromosome_13460_A_G,Chromosome_491591_A_T,Chromosome_491742_T_C,Chromosome_575679_A_G,Chromosome_575907_C_T,Chromosome_620625_A_G,Chromosome_657081_C_T,Chromosome_657142_C_T,Chromosome_657269_A_G,Chromosome_657578_A_G,Chromosome_734116_T_C,Chromosome_759746_C_T,Chromosome_760115_C_T,Chromosome_761155_C_T,Chromosome_762434_T_G,Chromosome_763031_T_C,Chromosome_763884_C_T,Chromosome_763886_C_A,Chromosome_764995_C_G,Chromosome_765150_G_A,Chromosome_765171_C_T,Chromosome_766645_A_C,Chromosome_775639_T_C,Chromosome_776100_G_A,Chromosome_776182_C_T,Chromosome_779615_G_C,Chromosome_781395_T_C,Chromosome_781687_A_G,Chromosome_800219_T_C,Chromosome_800357_C_A,Chromosome_1254562_A_G,Chromosome_1364706_G_A,Chromosome_1417019_C_T,Chromosome_1417554_G_C,Chromosome_1417793_G_A,Chromosome_1471659_C_T,Chromosome_1474001_C_T,Chromosome_1673425_C_T,Chromosome_1834177_A_C,Chromosome_1853974_C_T,Chromosome_1854045_A_G,Chromosome_1854300_T_C,Chromosome_1917972_A_G,Chromosome_2062922_T_C,Chromosome_2154724_C_A,Chromosome_2155168_C_G,Chromosome_2167926_A_G,Chromosome_2167983_C_T,Chromosome_2222308_T_C,Chromosome_2223293_T_C,Chromosome_2289047_G_A,Chromosome_2518076_C_T,Chromosome_2518132_C_T,Chromosome_2726051_G_A,Chromosome_2726105_G_A,Chromosome_2782498_G_A,Chromosome_3064632_G_A,Chromosome_3073868_T_C,Chromosome_3086788_T_C,Chromosome_3448714_G_C,Chromosome_3612813_T_C,Chromosome_3624486_T_C,Chromosome_3625065_T_G,Chromosome_3626562_G_A,Chromosome_4038287_G_A,Chromosome_4040517_A_G,Chromosome_4044872_G_A,Chromosome_4046007_C_T,Chromosome_4138377_A_G,Chromosome_4138622_G_A,Chromosome_4238675_C_T,Chromosome_4239298_C_T,Chromosome_4240671_C_T,Chromosome_4241042_A_G,Chromosome_4242075_G_A,Chromosome_4242643_C_T,Chromosome_4242803_G_C,Chromosome_4243460_C_T,Chromosome_4245969_C_T,Chromosome_4247429_A_G,Chromosome_4247646_A_C,Chromosome_4249408_G_A,Chromosome_4267647_T_C,Chromosome_4269387_T_G,Chromosome_4269606_A_G,Chromosome_4328492_G_A,Chromosome_4329782_G_A,Chromosome_4338603_G_A,Chromosome_4338732_G_A,Chromosome_4407588_T_C,Chromosome_4407873_C_A,Chromosome_4407927_T_G,Chromosome_4408156_A_C
ERR038257.vcf,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
ERR046771.vcf,0,1,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,0,1,1,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0
ERR046840.vcf,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
ERR046847.vcf,0,1,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,0,1,1,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0
ERR046937.vcf,0,1,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ERR4831907.vcf,0,1,0,1,0,0,1,0,0,0,1,0,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,1,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,0,0,1,0,1,1,0,1,0
ERR4831952.vcf,0,1,0,1,0,0,1,0,0,0,1,0,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,1,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0
ERR4831955.vcf,0,1,0,1,0,0,1,0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,0,0,0,0,1,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0
ERR4872232.vcf,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
ERR550776.vcf,0,1,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [37]:
df.to_csv("maf_prop_snp_matrix.csv")
print("📁 Saved SNP matrix to maf_prop_snp_matrix.csv")

📁 Saved SNP matrix to maf_prop_snp_matrix.csv